apiVersion: apps/v1
kind: Deployment
metadata:
  name: pensionerdetailapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PensionerDetailAPI
  template:
    metadata:
      labels:
        app: PensionerDetailAPI
    spec:
      containers:
      - name: pensionerdetailapi
        image: mypensionmanagementcr.azurecr.io/pensionerdetailapi:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: pensionmanagementsvc

---
apiVersion: v1
kind: Service
metadata:
  name: pensionerdetailapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PensionerDetailAPI